org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8 -Dkotlin.compiler.execution.strategy=in-process
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process

minecraft_version=1.20.1
enabled_platforms=forge

archives_base_name=ba_halo
mod_version=0.0.0-qsxhxxx
maven_group=com.ba_halo

architectury_version=9.1.12

fabric_loader_version=0.16.14
fabric_api_version=0.92.6+1.20.1

forge_version=1.20.1-47.2.1

kff_version=4.3.0



